# Pandas - Cleaning Empty Cells

In [107]:
import pandas as pd

+ `delim_whitespace = True` : allows pandas to automaticallu split columns by whitespace 
+ `index_col = 0` : removes the first column as the index

In [108]:
df = pd.read_csv('data.csv', delim_whitespace=True, index_col=0)
print(df.to_string())

                  Date  Pulse  Maxpulse  Calories
Duration
60        '2020/12/01'    110       130     409.1
60        '2020/12/02'    117       145     479.0
60        '2020/12/03'    103       135     340.0
45        '2020/12/04'    109       175     282.4
45        '2020/12/05'    117       148     406.0
60        '2020/12/06'    102       127     300.0
60        '2020/12/07'    110       136     374.0
450       '2020/12/08'    104       134     253.3
30        '2020/12/09'    109       133     195.1
60        '2020/12/10'     98       124     269.0
60        '2020/12/11'    103       147     329.3
60        '2020/12/12'    100       120     250.7
60        '2020/12/12'    100       120     250.7
60        '2020/12/13'    106       128     345.3
60        '2020/12/14'    104       132     379.3
60        '2020/12/15'     98       123     275.0
60        '2020/12/16'     98       120     215.2
60        '2020/12/17'    100       120     300.0
45        '2020/12/18'     90       112       NaN
60        '2020/12/19'    103       123     323.0
45        '2020/12/20'     97       125     243.0
60        '2020/12/21'    108       131     364.2
45                 NaN    100       119     282.0
60        '2020/12/23'    130       101     300.0
45        '2020/12/24'    105       132     246.0
60        '2020/12/25'    102       126     334.5
60          2020/12/26    100       120     250.0
60        '2020/12/27'     92       118     241.0
60        '2020/12/28'    103       132       NaN
60        '2020/12/29'    100       132     280.0
60        '2020/12/30'    102       129     380.3
60        '2020/12/31'     92       115     243.0

C:\Users\Huy\AppData\Local\Temp\ipykernel_5896\3160570690.py:1: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv('data.csv', delim_whitespace=True, index_col=0)

#### Remove Rows
+ One way to deal with empty cells is to remove rows that contain empty cells
+ The `dropna()` method returns a new DataFrame, and will not change the original
+ If you want to change the original DataFrame, use the `inplace = True` argument

In [109]:
newdf = df.dropna()
print(newdf.to_string())

                  Date  Pulse  Maxpulse  Calories
Duration
60        '2020/12/01'    110       130     409.1
60        '2020/12/02'    117       145     479.0
60        '2020/12/03'    103       135     340.0
45        '2020/12/04'    109       175     282.4
45        '2020/12/05'    117       148     406.0
60        '2020/12/06'    102       127     300.0
60        '2020/12/07'    110       136     374.0
450       '2020/12/08'    104       134     253.3
30        '2020/12/09'    109       133     195.1
60        '2020/12/10'     98       124     269.0
60        '2020/12/11'    103       147     329.3
60        '2020/12/12'    100       120     250.7
60        '2020/12/12'    100       120     250.7
60        '2020/12/13'    106       128     345.3
60        '2020/12/14'    104       132     379.3
60        '2020/12/15'     98       123     275.0
60        '2020/12/16'     98       120     215.2
60        '2020/12/17'    100       120     300.0
60        '2020/12/19'    103       123     323.0
45        '2020/12/20'     97       125     243.0
60        '2020/12/21'    108       131     364.2
60        '2020/12/23'    130       101     300.0
45        '2020/12/24'    105       132     246.0
60        '2020/12/25'    102       126     334.5
60          2020/12/26    100       120     250.0
60        '2020/12/27'     92       118     241.0
60        '2020/12/29'    100       132     280.0
60        '2020/12/30'    102       129     380.3
60        '2020/12/31'     92       115     243.0

In [110]:
df1 = pd.read_csv('data1.csv', delim_whitespace=True, index_col=0)
df1.dropna(inplace=True)
print(df1.to_string())

                  Date  Pulse  Maxpulse  Calories
Duration
60        '2020/12/01'    110       130     409.1
60        '2020/12/02'    117       145     479.0
60        '2020/12/03'    103       135     340.0
45        '2020/12/04'    109       175     282.4
45        '2020/12/05'    117       148     406.0
60        '2020/12/06'    102       127     300.0
60        '2020/12/07'    110       136     374.0
450       '2020/12/08'    104       134     253.3
30        '2020/12/09'    109       133     195.1
60        '2020/12/10'     98       124     269.0
60        '2020/12/11'    103       147     329.3
60        '2020/12/12'    100       120     250.7
60        '2020/12/12'    100       120     250.7
60        '2020/12/13'    106       128     345.3
60        '2020/12/14'    104       132     379.3
60        '2020/12/15'     98       123     275.0
60        '2020/12/16'     98       120     215.2
60        '2020/12/17'    100       120     300.0
60        '2020/12/19'    103       123     323.0
45        '2020/12/20'     97       125     243.0
60        '2020/12/21'    108       131     364.2
60        '2020/12/23'    130       101     300.0
45        '2020/12/24'    105       132     246.0
60        '2020/12/25'    102       126     334.5
60          2020/12/26    100       120     250.0
60        '2020/12/27'     92       118     241.0
60        '2020/12/29'    100       132     280.0
60        '2020/12/30'    102       129     380.3
60        '2020/12/31'     92       115     243.0

C:\Users\Huy\AppData\Local\Temp\ipykernel_5896\4118798995.py:1: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df1 = pd.read_csv('data1.csv', delim_whitespace=True, index_col=0)

#### Replace empty values
+ Another way of dealing with empty cells is to insert a value  instead
+ This way you do have to delete entries rows just because of empty cells
+ The `fillna()` method allows us to replace empty cell with a value

In [111]:
df = pd.read_csv('data1.csv', delim_whitespace=True, index_col=0)
df.fillna(130, inplace=True)
print(df.to_string())

                  Date  Pulse  Maxpulse  Calories
Duration
60        '2020/12/01'    110       130     409.1
60        '2020/12/02'    117       145     479.0
60        '2020/12/03'    103       135     340.0
45        '2020/12/04'    109       175     282.4
45        '2020/12/05'    117       148     406.0
60        '2020/12/06'    102       127     300.0
60        '2020/12/07'    110       136     374.0
450       '2020/12/08'    104       134     253.3
30        '2020/12/09'    109       133     195.1
60        '2020/12/10'     98       124     269.0
60        '2020/12/11'    103       147     329.3
60        '2020/12/12'    100       120     250.7
60        '2020/12/12'    100       120     250.7
60        '2020/12/13'    106       128     345.3
60        '2020/12/14'    104       132     379.3
60        '2020/12/15'     98       123     275.0
60        '2020/12/16'     98       120     215.2
60        '2020/12/17'    100       120     300.0
45        '2020/12/18'     90       112     130.0
60        '2020/12/19'    103       123     323.0
45        '2020/12/20'     97       125     243.0
60        '2020/12/21'    108       131     364.2
45                 130    100       119     282.0
60        '2020/12/23'    130       101     300.0
45        '2020/12/24'    105       132     246.0
60        '2020/12/25'    102       126     334.5
60          2020/12/26    100       120     250.0
60        '2020/12/27'     92       118     241.0
60        '2020/12/28'    103       132     130.0
60        '2020/12/29'    100       132     280.0
60        '2020/12/30'    102       129     380.3
60        '2020/12/31'     92       115     243.0

C:\Users\Huy\AppData\Local\Temp\ipykernel_5896\3167303131.py:1: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv('data1.csv', delim_whitespace=True, index_col=0)

#### Replace Only For Specified Columns

In [112]:
df = pd.read_csv('data1.csv', delim_whitespace=True, index_col=0)
df.fillna({"Calories" : 130}, inplace=True)
print(df.to_string())

                  Date  Pulse  Maxpulse  Calories
Duration
60        '2020/12/01'    110       130     409.1
60        '2020/12/02'    117       145     479.0
60        '2020/12/03'    103       135     340.0
45        '2020/12/04'    109       175     282.4
45        '2020/12/05'    117       148     406.0
60        '2020/12/06'    102       127     300.0
60        '2020/12/07'    110       136     374.0
450       '2020/12/08'    104       134     253.3
30        '2020/12/09'    109       133     195.1
60        '2020/12/10'     98       124     269.0
60        '2020/12/11'    103       147     329.3
60        '2020/12/12'    100       120     250.7
60        '2020/12/12'    100       120     250.7
60        '2020/12/13'    106       128     345.3
60        '2020/12/14'    104       132     379.3
60        '2020/12/15'     98       123     275.0
60        '2020/12/16'     98       120     215.2
60        '2020/12/17'    100       120     300.0
45        '2020/12/18'     90       112     130.0
60        '2020/12/19'    103       123     323.0
45        '2020/12/20'     97       125     243.0
60        '2020/12/21'    108       131     364.2
45                 NaN    100       119     282.0
60        '2020/12/23'    130       101     300.0
45        '2020/12/24'    105       132     246.0
60        '2020/12/25'    102       126     334.5
60          2020/12/26    100       120     250.0
60        '2020/12/27'     92       118     241.0
60        '2020/12/28'    103       132     130.0
60        '2020/12/29'    100       132     280.0
60        '2020/12/30'    102       129     380.3
60        '2020/12/31'     92       115     243.0

C:\Users\Huy\AppData\Local\Temp\ipykernel_5896\2010188218.py:1: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv('data1.csv', delim_whitespace=True, index_col=0)

#### Replace Using Mean, Median, or Mode

In [113]:
df = pd.read_csv('data1.csv', delim_whitespace=True, index_col=0)
x = df['Calories'].mean()
print(x)
df.fillna({"Calories" : x}, inplace=True)
df

304.68

C:\Users\Huy\AppData\Local\Temp\ipykernel_5896\26914332.py:1: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv('data1.csv', delim_whitespace=True, index_col=0)

                  Date  Pulse  Maxpulse  Calories
Duration
60        '2020/12/01'    110       130    409.10
60        '2020/12/02'    117       145    479.00
60        '2020/12/03'    103       135    340.00
45        '2020/12/04'    109       175    282.40
45        '2020/12/05'    117       148    406.00
60        '2020/12/06'    102       127    300.00
60        '2020/12/07'    110       136    374.00
450       '2020/12/08'    104       134    253.30
30        '2020/12/09'    109       133    195.10
60        '2020/12/10'     98       124    269.00
60        '2020/12/11'    103       147    329.30
60        '2020/12/12'    100       120    250.70
60        '2020/12/12'    100       120    250.70
60        '2020/12/13'    106       128    345.30
60        '2020/12/14'    104       132    379.30
60        '2020/12/15'     98       123    275.00
60        '2020/12/16'     98       120    215.20
60        '2020/12/17'    100       120    300.00
45        '2020/12/18'     90       112    304.68
60        '2020/12/19'    103       123    323.00
45        '2020/12/20'     97       125    243.00
60        '2020/12/21'    108       131    364.20
45                 NaN    100       119    282.00
60        '2020/12/23'    130       101    300.00
45        '2020/12/24'    105       132    246.00
60        '2020/12/25'    102       126    334.50
60          2020/12/26    100       120    250.00
60        '2020/12/27'     92       118    241.00
60        '2020/12/28'    103       132    304.68
60        '2020/12/29'    100       132    280.00
60        '2020/12/30'    102       129    380.30
60        '2020/12/31'     92       115    243.00

In [115]:
df = pd.read_csv('data1.csv', delim_whitespace=True, index_col=0)
x = df['Calories'].mode()[0]
df.fillna({"Calories" : x}, inplace=True)
print(df.to_string())

                  Date  Pulse  Maxpulse  Calories
Duration
60        '2020/12/01'    110       130     409.1
60        '2020/12/02'    117       145     479.0
60        '2020/12/03'    103       135     340.0
45        '2020/12/04'    109       175     282.4
45        '2020/12/05'    117       148     406.0
60        '2020/12/06'    102       127     300.0
60        '2020/12/07'    110       136     374.0
450       '2020/12/08'    104       134     253.3
30        '2020/12/09'    109       133     195.1
60        '2020/12/10'     98       124     269.0
60        '2020/12/11'    103       147     329.3
60        '2020/12/12'    100       120     250.7
60        '2020/12/12'    100       120     250.7
60        '2020/12/13'    106       128     345.3
60        '2020/12/14'    104       132     379.3
60        '2020/12/15'     98       123     275.0
60        '2020/12/16'     98       120     215.2
60        '2020/12/17'    100       120     300.0
45        '2020/12/18'     90       112     300.0
60        '2020/12/19'    103       123     323.0
45        '2020/12/20'     97       125     243.0
60        '2020/12/21'    108       131     364.2
45                 NaN    100       119     282.0
60        '2020/12/23'    130       101     300.0
45        '2020/12/24'    105       132     246.0
60        '2020/12/25'    102       126     334.5
60          2020/12/26    100       120     250.0
60        '2020/12/27'     92       118     241.0
60        '2020/12/28'    103       132     300.0
60        '2020/12/29'    100       132     280.0
60        '2020/12/30'    102       129     380.3
60        '2020/12/31'     92       115     243.0

C:\Users\Huy\AppData\Local\Temp\ipykernel_5896\1924204094.py:1: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv('data1.csv', delim_whitespace=True, index_col=0)